package miniJava.SyntacticAnalyzer;

public enum TokenKind {NUM, PLUS, TIMES, LPAREN, RPAREN, EOT, ERROR, CLASS, WHILE, IF, ELSE,
						THIS, BOOLEAN, PUBLIC, PRIVATE, STATIC, VOID, TRUE, FALSE, LBRACK,
						RBRACK, MINUS, DIVIDE, OR, AND, NOT, LESS, GREATER, EQUALS, NEQUALS,
						LEQUALS, GEQUALS, COMMA, INT, NEW, ASSIGN, ID, LCBRACK, RCBRACK, PERIOD,
						SEMIC, RETURN, NULL}

