  0         LOADL        0
  1         LOADL        -1
  2         CALL         L10
  3         HALT   (0)   
  4  L10:   PUSH         6
  5         LOADL        2
  6         CALL         newarr  
  7         STORE        3[LB]
  8         LOADL        1
  9         LOADL        1
 10         CALL         newobj  
 11         STORE        4[LB]
 12         LOAD         4[LB]
 13         LOADL        0
 14         LOADL        3
 15         CALL         fieldupd
 16         LOAD         3[LB]
 17         LOADL        0
 18         LOAD         4[LB]
 19         CALL         arrayupd
 20         LOADL        1
 21         LOADL        1
 22         CALL         newobj  
 23         STORE        5[LB]
 24         LOAD         5[LB]
 25         LOADL        0
 26         LOADL        5
 27         CALL         fieldupd
 28         LOAD         3[LB]
 29         LOADL        1
 30         LOAD         5[LB]
 31         CALL         arrayupd
 32         LOAD         3[LB]
 33         LOADL        0
 34         CALL         arrayref
 35         STORE        6[LB]
 36         LOAD         3[LB]
 37         LOADL        1
 38         CALL         arrayref
 39         STORE        7[LB]
 40         LOAD         6[LB]
 41         LOADL        0
 42         CALL         fieldref
 43         LOAD         7[LB]
 44         LOADL        0
 45         CALL         fieldref
 46         CALL         add     
 47         LOADL        13
 48         CALL         add     
 49         STORE        8[LB]
 50         LOAD         8[LB]
 51         CALL         putintnl
 52         RETURN (0)   1
