  0         LOADL        0
  1         LOADL        -1
  2         CALL         L10
  3         HALT   (0)   
  4  L10:   PUSH         2
  5         LOADL        1
  6         LOADL        2
  7         CALL         newobj  
  8         STORE        3[LB]
  9         LOAD         3[LB]
 10         LOADL        1
 11         LOADL        2
 12         LOADL        2
 13         CALL         newobj  
 14         CALL         fieldupd
 15         LOAD         3[LB]
 16         LOADL        1
 17         CALL         fieldref
 18         LOADL        1
 19         LOAD         3[LB]
 20         CALL         fieldupd
 21         LOAD         3[LB]
 22         LOADL        1
 23         CALL         fieldref
 24         LOADL        1
 25         CALL         fieldref
 26         LOADL        0
 27         LOADL        7
 28         CALL         fieldupd
 29         LOAD         3[LB]
 30         LOADL        0
 31         CALL         fieldref
 32         STORE        4[LB]
 33         LOAD         4[LB]
 34         CALL         putintnl
 35         RETURN (0)   1
